[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_22"]

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
